### ISSUE TITLE
TypeError when I run 'python train.py --cuda --isAddCostVolume --camNum 10'

### ISSUE THREAD

**Issue by Miles629** [lzqsd/TransparentShapeReconstruction#5]
I followed the readme guide and downloaded the dataset Images10.zip and Shapes.zip. Then I unzip the two zip files under the directory named 'Data'
I believe that I have made the right dataset path, and I have tested it by printing when data load .
Here is the question, when I run 'python train.py --cuda --isAddCostVolume --camNum 10', the console output the following:

(the  line number might be not correct, because I  inserted some code before ' for i, dataBatch in enumerate(brdfLoader):')

```
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    for i, dataBatch in enumerate(brdfLoader):
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ct/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/data/mcy/TransparentShapeReconstruction/Normal/dataLoader.py", line 286, in __getitem__
    env = cv2.imread(envFileName, -1)[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable
```
It seems that there are something wrong at:'for i, dataBatch in enumerate(brdfLoader):'

**Comment by Miles629** [comment]
It seems the error comes from `env = cv2.imread(envFileName, -1)[:, :, ::-1]`
I try to print it out and I find that:
envFileName: /home/zhl/CVPR20/TransparentShape/Data/Envmaps/train/826L.hdr
how to fix the envFileName?

**Comment by Miles629** [comment]
ok, I know what happened, I miss the envmaps,I got. slip
